### ISSUE TITLE
Can you give us a tutorial?

### ISSUE THREAD

**Issue by ghost** [osyrisrblx/RbxDiscordProxy#1]
Alot of people don't know how to use this. and I don't know how to use this.
and no way to execute the code for docker run in their website

**Comment by ghost** [comment]
@osyrisrblx It's been 21 days and you never respond? Or you're too busy like developing the game or doing something in your life?

Well I guess I'll wait

**Comment by osyrisrblx** [comment]
@James567894 For some reason I didn't get a notification about this, sorry!

I created a tutorial here a while back, might be worth moving into the README
https://devforum.roblox.com/t/roblox-discord-webhook-proxy-server/98825
